### ISSUE TITLE
Anglais

### ISSUE THREAD

**Issue by ronan-cariou** [yguitton/CP-Seeker#38]
Il doit  rester un « importation » dans le code pour information à l’utilisateur qu’il faut remplacer par « import » tout court.
Idem « exportation » en « export ».

**Comment by DamienCode404** [comment]
Avec la ligne de commande suivante : 

`findstr /s /i /m "mot_a_chercher" *.*`

- `/s` : Recherche récursive dans les sous-dossiers.
- `/i` : Recherche insensible à la casse (le mot peut être en majuscules ou en minuscules).
- `/m` : Affiche uniquement les noms des fichiers contenant le motif.
- `"mot_a_chercher"` : Le mot que l'on souhaite rechercher.
- `*.*` : Les étoiles servent à prendre en compte toutes les chaines de cratères en nom de fichier et en extension de fichier.

![image](https://github.com/yguitton/CP-Seeker/assets/116463750/d58e7d65-5c22-4091-ae70-4e76c8ecfffc)

Je vais donc modifier le mot "importation" dans le fichier "server\file.R" par "import" mais le mot "exportation" n'est pas présent dans les fichiers de codes "modifiables".

**Comment by ronan-cariou** [comment]
Ok je regarderai le résultat

**Comment by ronan-cariou** [comment]
Validé pour v2.1.3. J'archive l'issue.
