### ISSUE TITLE
Emplacements d'export et error.log

### ISSUE THREAD

**Issue by ronan-cariou** [yguitton/CP-Seeker#39]
Changer les adresses d'enregistrement des fichiers suivants :
EXPORT, Plutôt que "C:\Users\<user>\Documents\.CP-Seeker <2.1.2>", placer dans un dossier créé sous "<Racine_d'installation_de _l'appli>\CP-Seeker_<2.1.2>\export\"
ERROR LOG, Plutôt que "C:\Users\<user>\.CP-Seeker <2.1.2>", placer dans un dossier créé sous "...\CP-Seeker_2.0.0\Error_Log\"

**Comment by DamienCode404** [comment]
Changement des chemins vers les fichiers d'erreur et d'export à la racine du projet dans des répertoires dédiés.

- Error_log/error.log
- export/...

**Comment by jsaintvanne** [comment]
For me ok in https://github.com/yguitton/CP-Seeker/pull/47

**Comment by ronan-cariou** [comment]
Validé pour v2.1.3. J'archive l'issue.
