### ISSUE TITLE
Spécifier n° de version export Excel

### ISSUE THREAD

**Issue by ronan-cariou** [yguitton/CP-Seeker#40]
La cellule A1 des onglets de fichiers contient bien le numéro de version de CP-Seeker pour le template PCAs, mais il n'est pas précisé pour les templates PCOs et PXAs. A corriger.

**Comment by DamienCode404** [comment]
Test de la correction du code avec les PCOs :

![image](https://github.com/yguitton/CP-Seeker/assets/116463750/1b38ece5-42a4-43a0-8b13-eb35c6eeb4a0)

**Comment by jsaintvanne** [comment]
For me ok in https://github.com/yguitton/CP-Seeker/pull/47

**Comment by ronan-cariou** [comment]
Validé pour v2.1.3. J'archive l'issue.
