### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by ronan-cariou** [yguitton/CP-Seeker#42]
Faire en sorte que le error log ne soit pas écrasé à chaque réouverture de CP-Seeker. Il s'agirait de nommer le fichier "error_XXX" avec XXX donnant la date-heure-minute de création du fichier, i.e. à l'ouverture d'une session.

**Comment by DamienCode404** [comment]
Test du nouveau fichier de log avec la date au format jour-mois-année_heure-minutes :

![image](https://github.com/yguitton/CP-Seeker/assets/116463750/569b17dc-9ba4-4ab5-a513-dfde28e100c4)

**Comment by DamienCode404** [comment]
![image](https://github.com/yguitton/CP-Seeker/assets/116463750/40de45fb-3556-43d5-88d6-48906bd98e93)

**Comment by jsaintvanne** [comment]
For me ok in https://github.com/yguitton/CP-Seeker/pull/47

**Comment by ronan-cariou** [comment]
Validé pour v2.1.3. J'archive l'issue.
