### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by ronan-cariou** [yguitton/CP-Seeker#43]
Ajouter icône du user guide en haut à droite comme dans HaloSeeker. Mettre le user guide dans l’appli.

**Comment by DamienCode404** [comment]
Ajout de l'icone :
![image](https://github.com/yguitton/CP-Seeker/assets/116463750/c2e8b7d9-d7ff-426b-af6b-accdd41aaed7)

Lorsque l'on survole avec son curseur, on a les informations sur la documentation (à changer en fonction du pdf) : 
![image](https://github.com/yguitton/CP-Seeker/assets/116463750/d3e4d3a2-fc21-4713-9091-3c602a2f428b)
Dans le fichier ui.R ligne 24 : `title = 'CP-Seeker 2.1.2 documentation', `

Lorsque l'on clique sur le bouton, on ouvre la documentation dans chromium : 
![image](https://github.com/yguitton/CP-Seeker/assets/116463750/fa806d81-700c-401e-97d6-97fe336c1477)

Dans le fichier regpaths.json, nous avons le nom exact du fichier, sinon il ne sera pas détecté par l'application : 
`"documentation_file": "documentation.pdf"`

Message d'erreur si le document n'est pas présent : 
`if (is.null(reg_paths$documentation_file)) stop('Missing documentation file in file reg_paths.json')
`

**Comment by DamienCode404** [comment]
Changement du label pour ne pas avoir à préciser la version : 
![image](https://github.com/yguitton/CP-Seeker/assets/116463750/da241075-6374-4bb3-a1ee-0108adb5381d)

Documentation de CP-Seeker :
![image](https://github.com/yguitton/CP-Seeker/assets/116463750/e9a1c8f0-9bc5-47f4-9f80-370e6df5190a)

**Comment by jsaintvanne** [comment]
For me ok in https://github.com/yguitton/CP-Seeker/pull/47

**Comment by ronan-cariou** [comment]
Validé pour v2.1.3. J'archive l'issue.
