### ISSUE TITLE
Export csv, Nb chiffres après la virgule

### ISSUE THREAD

**Issue by ronan-cariou** [yguitton/CP-Seeker#54]
Dans l'export csv, la colonne "area" ne donne actuellement qu'un arrondi à l'unité, celle pour "deviation" un seul chiffre après la virgule. Coller à ce qui est fait pour l'export Excel, soit 6 chiffres après la virgule pour "area" et 2 chiffres après la virgule pour "deviation".

**Comment by DamienCode404** [comment]
Voir un exemple de sortie csv ci-dessous : 
[1_2024-03-26.csv](https://github.com/yguitton/CP-Seeker/files/14915425/1_2024-03-26.csv)

**Comment by DamienCode404** [comment]
Ah, mais du coup, je viens de voir que ce changement modifiait également l'affichage de la matrice de résultats :

Normalized Intensity (xE6)

![image](https://github.com/yguitton/CP-Seeker/assets/116463750/69115024-ad7d-440f-a3c2-2901b78986c5)

Deviation (mDa)

![image](https://github.com/yguitton/CP-Seeker/assets/116463750/6e33a2bd-e655-499e-9dbb-bae5f883ac08)


Est-ce que je cherche à retraiter l'affichage de la matrice affichée dans CP-Seeker ou on valide comme ça ?

**Comment by ronan-cariou** [comment]
Il faut conserver l'affichage de la matrice telle qu'elle était avant. Tu peux comparer le code entre l'export Excel et celui csv pour voir à quel niveau agir.
Ultérieurement, il y aura peut-être une issue sur l'ajout d'un paramètre d'affichage contrôlé par l'utilisateur pour définir le nombre de chiffres. Mais pas critique/prioritaire pour nous.

**Comment by DamienCode404** [comment]
![image](https://github.com/yguitton/CP-Seeker/assets/116463750/6d84fe80-0691-4a5c-b33e-8d79d014bb45)

**Comment by ronan-cariou** [comment]
Demande de modification bien prise en compte dans la v2.1.3.
Issue fermée.
